name: "Deploy and Release Bot"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

build_bot:
  image: ubuntu:latest
  before_script:
    - apt-get update && apt-get install -y curl file zip git
  script:
    # Build
    - chmod +x ./build.sh
    - ./build.sh

    # Clone scripts
    - git clone --branch v1.1 https://github.com/botcity-dev/cicd-pipeline-utils.git
    - chmod +x cicd-pipeline-utils/scripts/bot.sh

    # Deploy
    - cicd-pipeline-utils/scripts/bot.sh deploy -version "v1.2.0 -botFile "./bot.zip" -botId "ExampleBot" -type "python" -repository "DEFAULT"

    # Release
    - cicd-pipeline-utils/scripts/bot.sh release -version "v1.2.0 -botId "ExampleBot"
  variables:
    SERVER: $SERVER
    LOGIN: $LOGIN
    KEY: $KEY
